# library

In [15]:
import pandas as pd

In [16]:
data = pd.read_csv(r"D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\processed_customer_profile.csv")
data.head()

,CustomerID,FavoriteCategory,Gender,AgeGroup,Region,Recency,Frequency,Monetary
0,CUST00001,Electronics,Male,18-25,Surabaya,0,22,63882371
1,CUST00002,Beauty,Female,18-25,Medan,17,23,57227590
2,CUST00003,Home,Female,>50,Medan,21,28,76991379
3,CUST00004,Beauty,Female,18-25,Bandung,9,33,87579881
4,CUST00005,Electronics,Male,18-25,Yogyakarta,20,33,96718054

In [17]:
# recency
data['R_Score'] = pd.qcut(
    data['Recency'],
    q=4,
    labels=[4,3,2,1]
)

In [18]:
# Frequency
data['F_Score'] = pd.qcut(
    data['Frequency'],
    q=4,
    labels=[1,2,3,4]
)

In [19]:
# monetary
data['M_Score'] = pd.qcut(
    data['Monetary'],
    q=4,
    labels=[1,2,3,4]
)

In [20]:
data.head()

,CustomerID,FavoriteCategory,Gender,AgeGroup,Region,Recency,Frequency,Monetary,R_Score,F_Score,M_Score
0,CUST00001,Electronics,Male,18-25,Surabaya,0,22,63882371,4,2,3
1,CUST00002,Beauty,Female,18-25,Medan,17,23,57227590,3,2,2
2,CUST00003,Home,Female,>50,Medan,21,28,76991379,2,3,4
3,CUST00004,Beauty,Female,18-25,Bandung,9,33,87579881,3,4,4
4,CUST00005,Electronics,Male,18-25,Yogyakarta,20,33,96718054,2,4,4

In [22]:
# Membuat kolom RFM_Score dengan menggabungkan R_Score, F_Score, dan M_Score 
data['RFM_Score'] = (
    data['R_Score'].astype(str)
    + data['F_Score'].astype(str)
    + data['M_Score'].astype(str)
)

In [23]:
# membuat rules untuk segmentasi pelanggan berdasarkan RFM_Score    
def segment_customer(row):

    r = int(row['R_Score'])
    f = int(row['F_Score'])
    m = int(row['M_Score'])

    if r >= 3 and f >= 3 and m >= 3:
        return "Loyal Customer"

    elif r >= 2 and f >= 2:
        return "Potential Customer"

    elif r == 1:
        return "At Risk Customer"

    else:
        return "New Customer"

In [24]:
data['Segment'] = data.apply(
    segment_customer,
    axis=1
)

In [25]:
data.head()

,CustomerID,FavoriteCategory,Gender,AgeGroup,Region,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
0,CUST00001,Electronics,Male,18-25,Surabaya,0,22,63882371,4,2,3,423,Potential Customer
1,CUST00002,Beauty,Female,18-25,Medan,17,23,57227590,3,2,2,322,Potential Customer
2,CUST00003,Home,Female,>50,Medan,21,28,76991379,2,3,4,234,Potential Customer
3,CUST00004,Beauty,Female,18-25,Bandung,9,33,87579881,3,4,4,344,Loyal Customer
4,CUST00005,Electronics,Male,18-25,Yogyakarta,20,33,96718054,2,4,4,244,Potential Customer

In [26]:
data.to_csv(
    'D:\Sem 4\Rekomendasi Sistem\Tugas\PA\data\processed_customer_segmented.csv',
    index=False
)